# Generated by Django 6.0 on 2026-09-08 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id_externo", models.IntegerField(unique=True)),
                ("home_team", models.CharField(max_length=100)),
                ("away_team", models.CharField(max_length=100)),
                (
                    "home_team_crest",
                    models.URLField(blank=True, max_length=300, null=True),
                ),
                (
                    "away_team_crest",
                    models.URLField(blank=True, max_length=300, null=True),
                ),
                ("datetime", models.DateTimeField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("QUALIFYING", "Ronda Clasificatoria"),
                            ("QUALIFICATION_ROUND_1", "Ronda Clasificatoria 1"),
                            ("QUALIFICATION_ROUND_2", "Ronda Clasificatoria 2"),
                            ("QUALIFICATION_ROUND_3", "Ronda Clasificatoria 3"),
                            ("PLAYOFF_ROUND", "Playoff"),
                            ("GROUP_STAGE", "Fase de Grupos"),
                            ("LEAGUE_PHASE", "Fase de Liga"),
                            ("ROUND_OF_16", "Octavos de Final"),
                            ("QUARTER_FINALS", "Cuartos de Final"),
                            ("SEMI_FINALS", "Semifinales"),
                            ("THIRD_PLACE", "Tercer Lugar"),
                            ("FINAL", "Final"),
                        ],
                        max_length=30,
                    ),
                ),
                ("group", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Programado"),
                            ("TIMED", "Programado"),
                            ("IN_PLAY", "En Juego"),
                            ("PAUSED", "Pausado"),
                            ("FINISHED", "Finalizado"),
                            ("POSTPONED", "Pospuesto"),
                            ("SUSPENDED", "Suspendido"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("home_score", models.IntegerField(blank=True, null=True)),
                ("away_score", models.IntegerField(blank=True, null=True)),
                ("home_lineup", models.JSONField(blank=True, null=True)),
                ("away_lineup", models.JSONField(blank=True, null=True)),
                ("goals", models.JSONField(blank=True, null=True)),
                ("bookings", models.JSONField(blank=True, null=True)),
                ("substitutions", models.JSONField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, max_length=200, null=True)),
                ("attendance", models.IntegerField(blank=True, null=True)),
                ("injury_time", models.IntegerField(blank=True, null=True)),
                ("home_coach", models.CharField(blank=True, max_length=100, null=True)),
                ("away_coach", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "home_formation",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "away_formation",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("home_bench", models.JSONField(blank=True, null=True)),
                ("away_bench", models.JSONField(blank=True, null=True)),
                ("referees", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["datetime"],
            },
        ),
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="champions_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pick",
                    models.CharField(
                        choices=[
                            ("HOME", "1"),
                            ("DRAW", "X"),
                            ("AWAY", "2"),
                            ("HOME_OR_DRAW", "1X"),
                            ("DRAW_OR_AWAY", "X2"),
                            ("HOME_OR_AWAY", "12"),
                        ],
                        max_length=16,
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="champions.match",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="champions_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "match")},
            },
        ),
    ]
