# Generated by Django 6.0 on 2026-09-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("champions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="stage",
            field=models.CharField(
                choices=[
                    ("QUALIFYING", "Ronda Clasificatoria"),
                    ("QUALIFICATION_ROUND_1", "Ronda Clasificatoria 1"),
                    ("QUALIFICATION_ROUND_2", "Ronda Clasificatoria 2"),
                    ("QUALIFICATION_ROUND_3", "Ronda Clasificatoria 3"),
                    ("PLAYOFF_ROUND", "Playoff"),
                    ("GROUP_STAGE", "Fase de Grupos"),
                    ("LEAGUE_STAGE", "Fase de Liga"),
                    ("LEAGUE_PHASE", "Fase de Liga"),
                    ("ROUND_OF_16", "Octavos de Final"),
                    ("QUARTER_FINALS", "Cuartos de Final"),
                    ("SEMI_FINALS", "Semifinales"),
                    ("THIRD_PLACE", "Tercer Lugar"),
                    ("FINAL", "Final"),
                ],
                max_length=30,
            ),
        ),
    ]
