# Generated by Django 6.0.6 on 2026-06-10 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id_externo", models.IntegerField(unique=True)),
                ("home_team", models.CharField(max_length=100)),
                ("away_team", models.CharField(max_length=100)),
                ("datetime", models.DateTimeField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("PRELIMINARY_ROUND", "Preliminary Round"),
                            ("GROUP_STAGE", "Group Stage"),
                            ("ROUND_OF_16", "Round of 16"),
                            ("QUARTER_FINALS", "Quarter Finals"),
                            ("SEMI_FINALS", "Semi Finals"),
                            ("THIRD_PLACE", "Third Place"),
                            ("FINAL", "Final"),
                        ],
                        max_length=20,
                    ),
                ),
                ("group", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("TIMED", "Timed"),
                            ("IN_PLAY", "In Play"),
                            ("PAUSED", "Paused"),
                            ("FINISHED", "Finished"),
                            ("POSTPONED", "Postponed"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("home_score", models.IntegerField(blank=True, null=True)),
                ("away_score", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["datetime"],
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_goals", models.IntegerField()),
                ("away_goals", models.IntegerField()),
                ("points", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="worldcup.match"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "match")},
            },
        ),
    ]
