# Generated by Django 6.0 on 2026-06-10 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldcup", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="stage",
            field=models.CharField(
                choices=[
                    ("PRELIMINARY_ROUND", "Ronda Preliminar"),
                    ("GROUP_STAGE", "Fase de Grupos"),
                    ("ROUND_OF_16", "Octavos de Final"),
                    ("QUARTER_FINALS", "Cuartos de Final"),
                    ("SEMI_FINALS", "Semifinales"),
                    ("THIRD_PLACE", "Tercer Lugar"),
                    ("FINAL", "Final"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Programado"),
                    ("TIMED", "Programado"),
                    ("IN_PLAY", "En Juego"),
                    ("PAUSED", "Pausado"),
                    ("FINISHED", "Finalizado"),
                    ("POSTPONED", "Pospuesto"),
                    ("SUSPENDED", "Suspendido"),
                    ("CANCELLED", "Cancelado"),
                ],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("total_predictions", models.IntegerField(default=0)),
                ("exact_count", models.IntegerField(default=0)),
                ("winner_count", models.IntegerField(default=0)),
                ("goals_count", models.IntegerField(default=0)),
                ("accuracy", models.FloatField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
