# Generated by Django 6.0 on 2026-06-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldcup", "0002_alter_match_stage_alter_match_status_playerstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="away_lineup",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="away_team_crest",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="bookings",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="goals",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home_lineup",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home_team_crest",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="substitutions",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
