# Generated by Django 6.0 on 2026-06-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldcup", "0003_match_away_lineup_match_away_team_crest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="attendance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="away_bench",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="away_coach",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="away_formation",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="away_statistics",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home_bench",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home_coach",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home_formation",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home_statistics",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="injury_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="odds_away_win",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="odds_draw",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="odds_home_win",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="referees",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="venue",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
