# Generated by Django 6.0 on 2026-06-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "worldcup",
            "0004_match_attendance_match_away_bench_match_away_coach_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="away_statistics",
        ),
        migrations.RemoveField(
            model_name="match",
            name="home_statistics",
        ),
        migrations.RemoveField(
            model_name="match",
            name="odds_away_win",
        ),
        migrations.RemoveField(
            model_name="match",
            name="odds_draw",
        ),
        migrations.RemoveField(
            model_name="match",
            name="odds_home_win",
        ),
    ]
