# Generated by Django 6.0 on 2026-06-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldcup", "0006_add_friendship_invitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="group",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
