# Generated by Django 6.0 on 2026-06-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldcup", "0007_alter_match_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerstats",
            name="accuracy",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="current_streak",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="exact_count",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="goals_count",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="longest_streak",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="total_predictions",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="winner_count",
        ),
        migrations.AddField(
            model_name="playerstats",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
    ]
