from django import template

register = template.Library()

TEAM_NAMES_ES = {
    "Real Madrid": "Real Madrid",
    "Barcelona": "Barcelona",
    "Atlético Madrid": "Atlético de Madrid",
    "Atletico Madrid": "Atlético de Madrid",
    "Manchester City": "Manchester City",
    "Manchester United": "Manchester United",
    "Liverpool": "Liverpool",
    "Arsenal": "Arsenal",
    "Chelsea": "Chelsea",
    "Tottenham Hotspur": "Tottenham",
    "Bayern München": "Bayern Múnich",
    "Bayern Munich": "Bayern Múnich",
    "Borussia Dortmund": "Borussia Dortmund",
    "RB Leipzig": "RB Leipzig",
    "Bayer Leverkusen": "Bayer Leverkusen",
    "Paris Saint-Germain": "Paris Saint-Germain",
    "PSG": "PSG",
    "Marseille": "Marsella",
    "Juventus": "Juventus",
    "Inter": "Inter de Milán",
    "Internazionale": "Inter de Milán",
    "AC Milan": "AC Milan",
    "Napoli": "Nápoles",
    "Roma": "Roma",
    "Lazio": "Lazio",
    "Ajax": "Ajax",
    "PSV": "PSV",
    "Feyenoord": "Feyenoord",
    "Porto": "Oporto",
    "Benfica": "Benfica",
    "Sporting CP": "Sporting de Lisboa",
    "Sporting": "Sporting de Lisboa",
    "Club Brugge": "Brujas",
    "Anderlecht": "Anderlecht",
    "Celtic": "Celtic",
    "Rangers": "Rangers",
    "Galatasaray": "Galatasaray",
    "Fenerbahçe": "Fenerbahçe",
    "Fenerbahce": "Fenerbahçe",
    "Beşiktaş": "Besiktas",
    "Besiktas": "Besiktas",
    "Shakhtar Donetsk": "Shakhtar Donetsk",
    "Dynamo Kyiv": "Dinamo de Kiev",
    "Red Star Belgrade": "Estrella Roja de Belgrado",
    "Olympiacos": "Olympiacos",
    "PAOK": "PAOK",
    "Young Boys": "Young Boys",
    "Basel": "Basilea",
    "Salzburg": "Salzburgo",
    "Red Bull Salzburg": "Red Bull Salzburgo",
    "Copenhagen": "Copenhague",
    "FC Copenhagen": "FC Copenhagen",
    "Malmö": "Malmö",
    "Malmo": "Malmö",
    "Sheriff": "Sheriff",
    "Sheriff Tiraspol": "Sheriff Tiraspol",
    "Ludogorets": "Ludogorets",
    "Ferencváros": "Ferencváros",
    "Ferencvaros": "Ferencváros",
    "Slavia Praha": "Slavia Praga",
    "Slavia Prague": "Slavia Praga",
    "Sparta Praha": "Sparta Praga",
    "Sparta Prague": "Sparta Praga",
    "Legia Warszawa": "Legia de Varsovia",
    "Lech Poznań": "Lech Poznań",
    "Stuttgart": "Stuttgart",
    "Eintracht Frankfurt": "Eintracht Frankfurt",
    "Wolfsburg": "Wolfsburg",
    "Monaco": "Mónaco",
    "Lille": "Lille",
    "Lens": "Lens",
    "Sevilla": "Sevilla",
    "Real Sociedad": "Real Sociedad",
    "Real Betis": "Real Betis",
    "Villarreal": "Villarreal",
    "Valencia": "Valencia",
    "Athletic Bilbao": "Athletic Club",
    "Athletic Club": "Athletic Club",
    "Club Brugge KV": "Brujas",
    "Union Berlin": "Union Berlín",
    "Newcastle United": "Newcastle United",
    "Aston Villa": "Aston Villa",
    "Brighton": "Brighton",
    "West Ham": "West Ham",
    "Bologna": "Bolonia",
    "Atalanta": "Atalanta",
    "Fiorentina": "Fiorentina",
    "Torino": "Turín",
    "Monaco": "Mónaco",
    "Borussia Mönchengladbach": "Borussia Mönchengladbach",
    "Heidenheim": "Heidenheim",
    "Girona": "Girona",
    "Sturm Graz": "Sturm Graz",
    "Club Brugge": "Brujas",
    "Slovan Bratislava": "Slovan Bratislava",
    "Dinamo Zagreb": "Dinamo Zagreb",
    "Qarabag": "Qarabag",
    "Qarabag FK": "Qarabag",
    "Bodø/Glimt": "Bodø/Glimt",
    "Bodoe/Glimt": "Bodø/Glimt",
    "Pafos": "Pafos",
    "Pafos FC": "Pafos",
    "Kairat": "Kairat",
    "Kairat Almaty": "Kairat",
    "Midtjylland": "Midtjylland",
    "FC Midtjylland": "Midtjylland",
    "Brondby": "Brøndby",
    "Brøndby": "Brøndby",
    "Bodo/Glimt": "Bodø/Glimt",
}


@register.filter
def team_name_spanish(name):
    return TEAM_NAMES_ES.get(name, name)
